/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'use-cases': UseCase;
    publications: Publication;
    datasets: Dataset;
    indicators: Indicator;
    'indicator-values': IndicatorValue;
    posts: Post;
    'op-eds': OpEd;
    news: News;
    people: Person;
    organisations: Organisation;
    events: Event;
    'learning-resources': LearningResource;
    opportunities: Opportunity;
    newsletters: Newsletter;
    pages: Page;
    countries: Country;
    topics: Topic;
    enablers: Enabler;
    'rai-dimensions': RaiDimension;
    'stakeholder-types': StakeholderType;
    tags: Tag;
    'download-requests': DownloadRequest;
    subscribers: Subscriber;
    'event-registrations': EventRegistration;
    users: User;
    media: Media;
    search: Search;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    indicators: IndicatorsSelect<false> | IndicatorsSelect<true>;
    'indicator-values': IndicatorValuesSelect<false> | IndicatorValuesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'op-eds': OpEdsSelect<false> | OpEdsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'learning-resources': LearningResourcesSelect<false> | LearningResourcesSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    enablers: EnablersSelect<false> | EnablersSelect<true>;
    'rai-dimensions': RaiDimensionsSelect<false> | RaiDimensionsSelect<true>;
    'stakeholder-types': StakeholderTypesSelect<false> | StakeholderTypesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'download-requests': DownloadRequestsSelect<false> | DownloadRequestsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'site-settings': SiteSetting;
    home: Home;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'purge-expired-records': TaskPurgeExpiredRecords;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stage: 'concept' | 'pilot' | 'deployed' | 'scaled' | 'discontinued';
  yearStarted?: number | null;
  /**
   * The development problem addressed.
   */
  problem?: string | null;
  /**
   * How safety, rights, sustainability, inclusion and context were handled.
   */
  responsibleAiPractices?: string | null;
  /**
   * What is known about results, with sources where possible.
   */
  evidenceOfImpact?: string | null;
  organisations?: (number | Organisation)[] | null;
  people?: (number | Person)[] | null;
  /**
   * External links, for example a project site, a repository or press coverage.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  raiDimensions?: (number | RaiDimension)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  acronym?: string | null;
  stakeholderType: number | StakeholderType;
  observatoryRole?: ('lead' | 'partner' | 'funder' | 'member' | 'profiled') | null;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  website?: string | null;
  logo?: (number | null) | Media;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organisation categories. Government, private sector, civil society or NGO, university or research institution, regional or international body, and others the Client agrees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stakeholder-types".
 */
export interface StakeholderType {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images, PDFs and other files. Gated files require an email address before download.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen reader users. For documents, use the document title.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * Gated files ask for an email address and a consent tick before the file is released. Requests are stored in Download requests and can be exported.
   */
  access: 'open' | 'gated';
  /**
   * Purpose statement shown next to the form (Section 3.1.6 c).
   */
  gatePurpose?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Countries covered by the Observatory. ISO codes drive the map. The list is a seed pending client confirmation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * ISO 3166-1 alpha-3, for example LKA.
   */
  iso3: string;
  /**
   * ISO 3166-1 numeric as three digits, for example 144. Matches Natural Earth boundaries.
   */
  isoNumeric: string;
  subregion: 'south-asia' | 'southeast-asia';
  /**
   * Draw a marker on the map because the territory is too small to see at regional scale.
   */
  smallState?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sectors and thematic areas, for example health, education, agriculture, climate resilience.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Responsible AI ecosystem enablers used for mapping studies. Seeded with the six enablers in the Observatory description.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enablers".
 */
export interface Enabler {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Free keywords for cross-cutting themes, for example gender, disability, Indigenous communities, environment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * Position or role title.
   */
  role?: string | null;
  organisation?: (number | null) | Organisation;
  affiliation: 'team' | 'partner' | 'expert' | 'contributor' | 'advisory';
  summary: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  expertise?: (number | Topic)[] | null;
  photo?: (number | null) | Media;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  countries?: (number | Country)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  type:
    | 'report'
    | 'mapping-study'
    | 'annual-report'
    | 'research-brief'
    | 'policy-brief'
    | 'innovation-brief'
    | 'toolkit'
    | 'comparative-analysis';
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  abstract?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: (number | Person)[] | null;
  /**
   * Use when authors are not in the directory.
   */
  authorText?: string | null;
  organisations?: (number | Organisation)[] | null;
  /**
   * PDF or other file. Gating is set on the media item.
   */
  file?: (number | null) | Media;
  /**
   * If the publication lives elsewhere.
   */
  externalUrl?: string | null;
  citation?: string | null;
  pages?: number | null;
  cover?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  raiDimensions?: (number | RaiDimension)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Who produced the data.
   */
  source: string;
  /**
   * Method, coverage, caveats.
   */
  methodNotes?: string | null;
  /**
   * For example 2020 to 2025.
   */
  temporalCoverage?: string | null;
  updateFrequency?: string | null;
  licence?: ('cc-by-4' | 'cc-by-sa-4' | 'cc0' | 'odc' | 'restricted' | 'other') | null;
  files?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * External access, view or API links.
   */
  accessLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  indicators?: (number | Indicator)[] | null;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each indicator is shown as a regional map, a chart and a table. Values are entered as indicator values.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicators".
 */
export interface Indicator {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * What the indicator measures and how to read it.
   */
  definition: string;
  /**
   * For example score 0 to 100, count, percent, USD million.
   */
  unit: string;
  valueType: 'number' | 'percent' | 'status';
  min?: number | null;
  max?: number | null;
  higherIsBetter?: boolean | null;
  /**
   * For status indicators. Map numeric codes to labels, for example 0 None, 1 Draft, 2 Adopted.
   */
  statusLabels?:
    | {
        code: number;
        label: string;
        id?: string | null;
      }[]
    | null;
  enabler?: (number | null) | Enabler;
  topics?: (number | Topic)[] | null;
  /**
   * Producer of the underlying data.
   */
  source: string;
  sourceUrl?: string | null;
  methodology?: string | null;
  dataset?: (number | null) | Dataset;
  /**
   * Show on the Data and Maps landing page.
   */
  featured?: boolean | null;
  order?: number | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate?: string | null;
  timezone?: string | null;
  format: 'online' | 'in-person' | 'hybrid';
  eventType?: ('dialogue' | 'webinar' | 'workshop' | 'convening' | 'scopeathon' | 'cop') | null;
  venue?: string | null;
  /**
   * Meeting or stream link, shown to registrants.
   */
  onlineUrl?: string | null;
  registration?: {
    mode?: ('none' | 'form' | 'external') | null;
    externalUrl?: string | null;
    closesAt?: string | null;
    capacity?: number | null;
  };
  organisations?: (number | Organisation)[] | null;
  speakers?: (number | Person)[] | null;
  recordingUrl?: string | null;
  image?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-resources".
 */
export interface LearningResource {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  resourceType: 'course' | 'video' | 'toolkit' | 'guide' | 'framework' | 'reading-list';
  level?: ('introductory' | 'intermediate' | 'advanced') | null;
  /**
   * For example 2 hours or 6 weeks.
   */
  duration?: string | null;
  provider?: string | null;
  providerOrganisation?: (number | null) | Organisation;
  externalUrl?: string | null;
  file?: (number | null) | Media;
  /**
   * YouTube or Vimeo page URL.
   */
  videoEmbedUrl?: string | null;
  language?: string | null;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  raiDimensions?: (number | RaiDimension)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Qualities of responsible AI. Seeded with safe, rights-based, sustainable, inclusive and context-appropriate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rai-dimensions".
 */
export interface RaiDimension {
  id: number;
  name: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One row per indicator, country and year. Bulk import is available through the API or the import script.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicator-values".
 */
export interface IndicatorValue {
  id: number;
  /**
   * Generated.
   */
  label?: string | null;
  indicator: number | Indicator;
  country: number | Country;
  year: number;
  value: number;
  /**
   * Caveat shown in the table, for example provisional.
   */
  note?: string | null;
  /**
   * Row-level source if different from the indicator source.
   */
  sourceUrl?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors?: (number | Person)[] | null;
  authorText?: string | null;
  image?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "op-eds".
 */
export interface OpEd {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  /**
   * Where it was published.
   */
  outlet: string;
  externalUrl: string;
  authors?: (number | Person)[] | null;
  authorText?: string | null;
  image?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors?: (number | Person)[] | null;
  authorText?: string | null;
  image?: (number | null) | Media;
  relatedUseCases?: (number | UseCase)[] | null;
  relatedPublications?: (number | Publication)[] | null;
  relatedDatasets?: (number | Dataset)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedLearning?: (number | LearningResource)[] | null;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  opportunityType: 'fellowship' | 'grant' | 'programme' | 'call-for-papers' | 'job' | 'competition' | 'event';
  deadline?: string | null;
  rolling?: boolean | null;
  provider: string;
  eligibility?: string | null;
  externalUrl: string;
  countries?: (number | Country)[] | null;
  /**
   * Sector or thematic area.
   */
  topics?: (number | Topic)[] | null;
  /**
   * Responsible AI ecosystem enabler(s).
   */
  enablers?: (number | Enabler)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  issueNumber: number;
  /**
   * One to three sentences. Shown in listings, search results and social previews.
   */
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pdf?: (number | null) | Media;
  /**
   * Web version hosted by the email provider, if any.
   */
  externalUrl?: string | null;
  featured?:
    | (
        | {
            relationTo: 'use-cases';
            value: number | UseCase;
          }
        | {
            relationTo: 'publications';
            value: number | Publication;
          }
        | {
            relationTo: 'events';
            value: number | Event;
          }
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'opportunities';
            value: number | Opportunity;
          }
      )[]
    | null;
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL identifier. Generated from the title, editable.
   */
  slug?: string | null;
  summary?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  provenance?: ('sample' | 'public' | 'client') | null;
  /**
   * Optional overrides for search engines and social sharing (Section 3.1.6 e).
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Records created by the email-gated download form. Export as CSV from the list view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-requests".
 */
export interface DownloadRequest {
  id: number;
  email: string;
  file: number | Media;
  resourceTitle?: string | null;
  resourceUrl?: string | null;
  organisation?: string | null;
  country?: string | null;
  consentText: string;
  consentVersion: string;
  /**
   * One-way hash for abuse detection. Not reversible.
   */
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscriptions. Also synced to the configured email provider. Export as CSV from the list view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  organisation?: string | null;
  interests?: (number | Topic)[] | null;
  status: 'pending' | 'subscribed' | 'unsubscribed';
  /**
   * Which provider adapter handled this subscription.
   */
  provider?: string | null;
  providerId?: string | null;
  consentText: string;
  consentVersion: string;
  /**
   * Page the form was submitted from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registrations submitted through on-site event forms. Export as CSV from the list view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  organisation?: string | null;
  country?: string | null;
  stakeholderType?: (number | null) | StakeholderType;
  accessibilityNeeds?: string | null;
  consentText: string;
  consentVersion: string;
  status?: ('registered' | 'waitlisted' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrator manages users and settings. Editor publishes and archives content and exports records. Contributor drafts content.
   */
  role: 'admin' | 'editor' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Unified search index, maintained automatically on every save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'use-cases';
        value: number | UseCase;
      }
    | {
        relationTo: 'publications';
        value: number | Publication;
      }
    | {
        relationTo: 'datasets';
        value: number | Dataset;
      }
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'op-eds';
        value: number | OpEd;
      }
    | {
        relationTo: 'news';
        value: number | News;
      }
    | {
        relationTo: 'people';
        value: number | Person;
      }
    | {
        relationTo: 'organisations';
        value: number | Organisation;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      }
    | {
        relationTo: 'learning-resources';
        value: number | LearningResource;
      }
    | {
        relationTo: 'opportunities';
        value: number | Opportunity;
      }
    | {
        relationTo: 'newsletters';
        value: number | Newsletter;
      }
    | {
        relationTo: 'indicators';
        value: number | Indicator;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      };
  excerpt?: string | null;
  /**
   * Taxonomy names and type label, used for matching.
   */
  keywords?: string | null;
  typeLabel?: string | null;
  path?: string | null;
  countries?: string | null;
  topics?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'en') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'purge-expired-records' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'purge-expired-records' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'use-cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'indicators';
        value: number | Indicator;
      } | null)
    | ({
        relationTo: 'indicator-values';
        value: number | IndicatorValue;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'op-eds';
        value: number | OpEd;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'learning-resources';
        value: number | LearningResource;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'enablers';
        value: number | Enabler;
      } | null)
    | ({
        relationTo: 'rai-dimensions';
        value: number | RaiDimension;
      } | null)
    | ({
        relationTo: 'stakeholder-types';
        value: number | StakeholderType;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'download-requests';
        value: number | DownloadRequest;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  stage?: T;
  yearStarted?: T;
  problem?: T;
  responsibleAiPractices?: T;
  evidenceOfImpact?: T;
  organisations?: T;
  people?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  image?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  raiDimensions?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  summary?: T;
  abstract?: T;
  authors?: T;
  authorText?: T;
  organisations?: T;
  file?: T;
  externalUrl?: T;
  citation?: T;
  pages?: T;
  cover?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  raiDimensions?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  source?: T;
  methodNotes?: T;
  temporalCoverage?: T;
  updateFrequency?: T;
  licence?: T;
  files?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  accessLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  indicators?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicators_select".
 */
export interface IndicatorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  definition?: T;
  unit?: T;
  valueType?: T;
  min?: T;
  max?: T;
  higherIsBetter?: T;
  statusLabels?:
    | T
    | {
        code?: T;
        label?: T;
        id?: T;
      };
  enabler?: T;
  topics?: T;
  source?: T;
  sourceUrl?: T;
  methodology?: T;
  dataset?: T;
  featured?: T;
  order?: T;
  provenance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicator-values_select".
 */
export interface IndicatorValuesSelect<T extends boolean = true> {
  label?: T;
  indicator?: T;
  country?: T;
  year?: T;
  value?: T;
  note?: T;
  sourceUrl?: T;
  provenance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  authors?: T;
  authorText?: T;
  image?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "op-eds_select".
 */
export interface OpEdsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  outlet?: T;
  externalUrl?: T;
  authors?: T;
  authorText?: T;
  image?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  authors?: T;
  authorText?: T;
  image?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  organisation?: T;
  affiliation?: T;
  summary?: T;
  bio?: T;
  expertise?: T;
  photo?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  countries?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  acronym?: T;
  stakeholderType?: T;
  observatoryRole?: T;
  summary?: T;
  description?: T;
  website?: T;
  logo?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  timezone?: T;
  format?: T;
  eventType?: T;
  venue?: T;
  onlineUrl?: T;
  registration?:
    | T
    | {
        mode?: T;
        externalUrl?: T;
        closesAt?: T;
        capacity?: T;
      };
  organisations?: T;
  speakers?: T;
  recordingUrl?: T;
  image?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-resources_select".
 */
export interface LearningResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  resourceType?: T;
  level?: T;
  duration?: T;
  provider?: T;
  providerOrganisation?: T;
  externalUrl?: T;
  file?: T;
  videoEmbedUrl?: T;
  language?: T;
  relatedUseCases?: T;
  relatedPublications?: T;
  relatedDatasets?: T;
  relatedEvents?: T;
  relatedLearning?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  raiDimensions?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  opportunityType?: T;
  deadline?: T;
  rolling?: T;
  provider?: T;
  eligibility?: T;
  externalUrl?: T;
  countries?: T;
  topics?: T;
  enablers?: T;
  tags?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  issueNumber?: T;
  summary?: T;
  body?: T;
  pdf?: T;
  externalUrl?: T;
  featured?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  publishedAt?: T;
  provenance?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  iso3?: T;
  isoNumeric?: T;
  subregion?: T;
  smallState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enablers_select".
 */
export interface EnablersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rai-dimensions_select".
 */
export interface RaiDimensionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stakeholder-types_select".
 */
export interface StakeholderTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-requests_select".
 */
export interface DownloadRequestsSelect<T extends boolean = true> {
  email?: T;
  file?: T;
  resourceTitle?: T;
  resourceUrl?: T;
  organisation?: T;
  country?: T;
  consentText?: T;
  consentVersion?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  organisation?: T;
  interests?: T;
  status?: T;
  provider?: T;
  providerId?: T;
  consentText?: T;
  consentVersion?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  organisation?: T;
  country?: T;
  stakeholderType?: T;
  accessibilityNeeds?: T;
  consentText?: T;
  consentVersion?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  access?: T;
  gatePurpose?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  keywords?: T;
  typeLabel?: T;
  path?: T;
  countries?: T;
  topics?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  description?: string | null;
  contactEmail?: string | null;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the footer. Logos pending Client-supplied assets.
   */
  funders?:
    | {
        name: string;
        url?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        name: string;
        url?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  programmeNote?: string | null;
  /**
   * Show "sample content" and "pending confirmation" labels. Turn off when real content is loaded.
   */
  showPrototypeNotices?: boolean | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    url?: string | null;
  };
  /**
   * Change when consent wording changes. Stored with every record.
   */
  consentVersion: string;
  newsletterConsentText: string;
  downloadConsentText: string;
  registrationConsentText: string;
  /**
   * How long download and registration records are kept.
   */
  retentionMonths?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  headline: string;
  intro: string;
  /**
   * Up to four items for the lead positions.
   */
  featured?:
    | (
        | {
            relationTo: 'use-cases';
            value: number | UseCase;
          }
        | {
            relationTo: 'publications';
            value: number | Publication;
          }
        | {
            relationTo: 'datasets';
            value: number | Dataset;
          }
        | {
            relationTo: 'events';
            value: number | Event;
          }
        | {
            relationTo: 'posts';
            value: number | Post;
          }
      )[]
    | null;
  /**
   * Indicator shown in the home page map.
   */
  featuredIndicator?: (number | null) | Indicator;
  /**
   * Entry points by audience (Section 2.2 of the RFP). Order and set are pending confirmation in requirements refinement.
   */
  audienceEntries?:
    | {
        label: string;
        description: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  contactEmail?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  funders?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  programmeNote?: T;
  showPrototypeNotices?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        url?: T;
      };
  consentVersion?: T;
  newsletterConsentText?: T;
  downloadConsentText?: T;
  registrationConsentText?: T;
  retentionMonths?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  featured?: T;
  featuredIndicator?: T;
  audienceEntries?:
    | T
    | {
        label?: T;
        description?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurge-expired-records".
 */
export interface TaskPurgeExpiredRecords {
  input?: unknown;
  output: {
    cutoff?: string | null;
    months?: number | null;
    downloadRequests?: number | null;
    eventRegistrations?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'use-cases'
      | 'publications'
      | 'datasets'
      | 'indicators'
      | 'indicator-values'
      | 'posts'
      | 'op-eds'
      | 'news'
      | 'people'
      | 'organisations'
      | 'events'
      | 'learning-resources'
      | 'opportunities'
      | 'newsletters'
      | 'pages'
      | 'countries'
      | 'topics'
      | 'enablers'
      | 'rai-dimensions'
      | 'stakeholder-types'
      | 'tags'
      | 'download-requests'
      | 'subscribers'
      | 'event-registrations'
      | 'users'
      | 'media'
      | 'search'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'use-cases';
          value: number | UseCase;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null)
      | ({
          relationTo: 'datasets';
          value: number | Dataset;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'op-eds';
          value: number | OpEd;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'people';
          value: number | Person;
        } | null)
      | ({
          relationTo: 'organisations';
          value: number | Organisation;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'learning-resources';
          value: number | LearningResource;
        } | null)
      | ({
          relationTo: 'opportunities';
          value: number | Opportunity;
        } | null)
      | ({
          relationTo: 'newsletters';
          value: number | Newsletter;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}